### ISSUE TITLE
Design database models

### ISSUE THREAD

**Issue by yuler** [yuler/store#6]
# 设计数据库，必须的表

- products
- orders
- users
- categories
- tags
- ...

# 由于项目初期使用 [云数据库](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/capabilities.html#%E6%95%B0%E6%8D%AE%E5%BA%93)

所以需要 databse migrate 的机制，方便快速初始化 database

refs:

- https://github.com/golang-migrate/migrate
- https://github.com/db-migrate/node-db-migrate

**Comment by enya-yy** [comment]
# 初步筛选统计了一下，共计26张表

## 商品相关
+ 商品表(product, merch, goods???)
+ 分类表(category)
+ 商品属性表(product_attribute)
+ 商品图片信息表(product_image)
+ 商品常见问题表(product_question)
+ 商品规格表(product_type)
+ 商品评论表(product_comment)
+ 商品评论图片表(product_comment_images)
+ 商品品牌表((product_brand)

## 搜索相关
+ 搜索关键词列表(search_keywords)
+ 搜索记录表(search_history)

## 订单相关
+ 订单表(order)
+ 订单商品信息表(order_infos)

## 快递相关
+ 物流信息表(exress)
+ 快递公司表(express_company)

## 优惠券相关
+ 优惠券列表(coupon)
+ 用户优惠券信息表(user_coui)

## 用户相关
+ 后台管理用表(admin)
+ 用户表(user)
+ 用户类型表(user_type)
+ 用户反馈表(user_feedback)
+ 用户收货地址表(user_address)
+ 用户关注商品表(user_follow)

## 其他
+ 购物车列表(cart)
+ 省市区表(region)
+ 轮播广告表(advertise)

**Comment by yuler** [comment]
那咱们先等商品的？

你这个是不是太复杂了。

## 商品相关

products
product_skus
product_comments

我觉得就这几张就行了，需要那么多吗？
